package defpackage;

/* compiled from: PG */
/* renamed from: b  reason: default package */
/* loaded from: classes.dex */
public final class b {
    public int b;
    public int c;
    int d;
    public boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(a aVar) {
        aVar.d = this.h;
        aVar.e = this.i;
        aVar.f = this.j;
        aVar.g = this.k;
        aVar.h = this.l;
        aVar.i = this.m;
        aVar.j = this.n;
        aVar.k = this.o;
        aVar.l = this.p;
        aVar.m = this.q;
        aVar.n = this.r;
        aVar.o = this.s;
        aVar.p = this.t;
        aVar.leftMargin = this.A;
        aVar.rightMargin = this.B;
        aVar.topMargin = this.C;
        aVar.bottomMargin = this.D;
        aVar.u = this.M;
        aVar.v = this.L;
        aVar.w = this.u;
        aVar.x = this.v;
        aVar.y = this.w;
        aVar.K = this.x;
        aVar.L = this.y;
        aVar.B = this.N;
        aVar.A = this.O;
        aVar.D = this.Q;
        aVar.C = this.P;
        aVar.E = this.ad;
        aVar.F = this.ae;
        aVar.I = this.af;
        aVar.J = this.ag;
        aVar.G = this.ah;
        aVar.H = this.ai;
        aVar.M = this.z;
        aVar.c = this.g;
        aVar.a = this.e;
        aVar.b = this.f;
        aVar.width = this.b;
        aVar.height = this.c;
        aVar.setMarginStart(this.F);
        aVar.setMarginEnd(this.E);
        aVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        b bVar = new b();
        bVar.a = this.a;
        bVar.b = this.b;
        bVar.c = this.c;
        bVar.e = this.e;
        bVar.f = this.f;
        bVar.g = this.g;
        bVar.h = this.h;
        bVar.i = this.i;
        bVar.j = this.j;
        bVar.k = this.k;
        bVar.l = this.l;
        bVar.m = this.m;
        bVar.n = this.n;
        bVar.o = this.o;
        bVar.p = this.p;
        bVar.q = this.q;
        bVar.r = this.r;
        bVar.s = this.s;
        bVar.t = this.t;
        bVar.u = this.u;
        bVar.v = this.v;
        bVar.w = this.w;
        bVar.x = this.x;
        bVar.y = this.y;
        bVar.u = this.u;
        bVar.u = this.u;
        bVar.u = this.u;
        bVar.u = this.u;
        bVar.u = this.u;
        bVar.z = this.z;
        bVar.A = this.A;
        bVar.B = this.B;
        bVar.C = this.C;
        bVar.D = this.D;
        bVar.E = this.E;
        bVar.F = this.F;
        bVar.G = this.G;
        bVar.H = this.H;
        bVar.I = this.I;
        bVar.J = this.J;
        bVar.K = this.K;
        bVar.L = this.L;
        bVar.M = this.M;
        bVar.N = this.N;
        bVar.O = this.O;
        bVar.P = this.P;
        bVar.Q = this.Q;
        bVar.R = this.R;
        bVar.S = this.S;
        bVar.T = this.T;
        bVar.U = this.U;
        bVar.V = this.V;
        bVar.W = this.W;
        bVar.X = this.X;
        bVar.Y = this.Y;
        bVar.Z = this.Z;
        bVar.aa = this.aa;
        bVar.ab = this.ab;
        bVar.ac = this.ac;
        bVar.ad = this.ad;
        bVar.ae = this.ae;
        bVar.af = this.af;
        bVar.ag = this.ag;
        bVar.ah = this.ah;
        bVar.ai = this.ai;
        return bVar;
    }
}
