package defpackage;

/* compiled from: PG */
/* renamed from: blf  reason: default package */
/* loaded from: classes.dex */
public final class blf implements ble {
    public final String toString() {
        return "Feature: APA_DATA_DOWNLOAD_API_VELVET true\nAPA_INVOCATION_APIS true\nAPA_MOSAIC_API true\nAPA_OPA_HANDOVER true\nAPP_ACTIONS_SERVICE true\nAPP_SHORTCUT_DEEPLINK true\nAPP_VOICE_CONTROL true\nFACEVIEWER true\nFEDASS true\nHANDS_FREE_MANAGER true\nNGA_APA_DATA_DOWNLOAD_GRPC true\nNGA_ONDEVICE_NLU_FULFILLMENT_SERVICE true\nOPA_ANDROID_MORRIS true\nOPA_ANDROID_MORRIS_OOBE true\nOPA_SHORTCUTS true\nTACTILE true\nTAPAS_IN_NGA true\nTCLIB_NATIVE_SPLIT true\nTNG_AMBIENT_ASSISTANT true\nTNG_APPCONTROL_INFRA_SATIN true\nTNG_ASSISTANT_CUSTODIO true\nTNG_ASSISTANT_POWERED_VOICE_SEARCH true\nTNG_AUTOBOT true\nTNG_CONTEXT_DEBUG true\nTNG_DICTATION true\nTNG_HSI true\nTNG_KARAJAN true\nTNG_MAIN_ASSISTANT_SATIN true\nTNG_MAIN_ASSISTANT_VELVET true\nTNG_PODCASTS true\nTNG_PRONUNCIATION_LEARNING true\nTNG_REMINDERS true\nTNG_ROTI true\nTNG_SMART_SETUP_DEEPLINK true\nTNG_SOUND_SEARCH_CLOUD_SEARCH_NOW_PLAYING true\nTNG_WEATHER_WIDGET true\nTNG_WEBGLIDE true\nTNG_XBLEND true\nWARM_ACTIONS true\n";
    }
}
