package defpackage;

/* compiled from: PG */
/* renamed from: ctg  reason: default package */
/* loaded from: classes.dex */
public enum ctg implements ids {
    CONV2QUERY_FEATURIZE_CANDIDATE,
    EXT_GIF_ACTIVATE,
    EXT_GIF_KB_ACTIVATE,
    EXT_GIF_DEACTIVATE,
    EXT_CARD_ACTIVATE,
    EXT_CARD_KB_ACTIVATE,
    EXT_CARD_DEACTIVATE,
    EXT_STICKER_ACTIVATE,
    EXT_STICKER_KB_ACTIVATE,
    EXT_STICKER_DEACTIVATE,
    FEDERATEDC2Q_EXTENSION_ON_CREATE_APP,
    FEDERATEDC2Q_EXTENSION_ON_CREATE_SERVICE,
    FEDERATEDC2Q_EXTENSION_ON_START_INPUT_VIEW,
    FEDERATEDC2Q_EXTENSION_EXTRA_CANDIDATES_INITIALIZE,
    FEDERATEDC2Q_EXTENSION_EXTRA_CANDIDATES_GENERATE,
    EXT_BITMOJI_ACTIVATE,
    EXT_BITMOJI_KB_ACTIVATE,
    EXT_BITMOJI_DEACTIVATE,
    EXT_EMOJIDATA_ACTIVATE,
    EXT_EMOJIDATA_DEACTIVATE,
    EXT_EMOJI_ACTIVATE,
    EXT_EMOJI_KB_ACTIVATE,
    EXT_EMOJI_DEACTIVATE,
    EXT_EMOJI_1ST_STARTUP,
    EXT_EMOJI_2ND_OR_LATER_STARTUP,
    GIF_EXTENSION_SHOWN_TIME,
    EMOJI_SEARCH_EXTENSION_SHOWN_TIME,
    EXT_UNIVERSAL_MEDIA_ACTIVATE,
    EXT_UNIVERSAL_MEDIA_KB_ACTIVATE,
    EXT_UNIVERSAL_MEDIA_DEACTIVATE,
    UNIVERSAL_MEDIA_RECENT_EMOJI_FETCHER_TIME,
    UNIVERSAL_MEDIA_RECENT_GIF_FETCHER_TIME,
    UNIVERSAL_MEDIA_RECENT_STICKER_FETCHER_TIME,
    UNIVERSAL_MEDIA_SEARCH_EMOJI_FETCHER_TIME,
    UNIVERSAL_MEDIA_SEARCH_GIF_FETCHER_TIME,
    UNIVERSAL_MEDIA_SEARCH_STICKER_FETCHER_TIME,
    UNIVERSAL_MEDIA_DATA_READY_TIME,
    EXPRESSIVE_STICKER_CLIENT_INITIALIZE,
    EXPRESSIVE_STICKER_CLIENT_SYNC,
    IMAGE_DOWNLOAD_TIME_GIF_SUCCESS,
    IMAGE_DOWNLOAD_TIME_GIF_FAILURE,
    IMAGE_DOWNLOAD_TIME_THUMBNAIL_SUCCESS,
    IMAGE_DOWNLOAD_TIME_THUMBNAIL_FAILURE,
    STICKERS_EXPRESSIVE_FETCHER_GET_PACKS,
    STICKERS_EXPRESSIVE_FETCHER_SEARCH,
    STICKERS_EXPRESSIVE_FETCHER_SUGGEST,
    STICKERS_BITMOJI_FETCHER_GET_PACKS,
    STICKERS_BITMOJI_FETCHER_GET_PACKS_ALL,
    STICKERS_BITMOJI_FETCHER_GET_PACKS_FAVORITES,
    STICKERS_BITMOJI_FETCHER_GET_PACKS_REFRESH_CACHE,
    STICKERS_BITMOJI_FETCHER_SEARCH,
    STICKERS_BITMOJI_FETCHER_SUGGEST,
    STICKERS_BITMOJI_CONTEXTUAL_FETCHER_GET_CONTEXTUAL_PACKS,
    STICKERS_BITMOJI_FETCHER_GET_STATUS,
    STICKERS_MULTI_FETCHER_GET_PACKS,
    STICKERS_MULTI_FETCHER_SEARCH,
    STICKERS_MULTI_FETCHER_SUGGEST,
    BITMOJI_IMAGE_OPEN_INPUTSTREAM,
    STICKERS_BITMOJI_CACHE_STORE_GET_PACKS,
    CONTENT_CACHE_DOWNLOAD_TASK,
    USAGE_HISTOGRAM_STORE_INCREMENT_COUNTER,
    FAST_ACCESS_BAR_ACTIVATE,
    FAST_ACCESS_BAR_FETCH_FREQUENT_EMOJIS,
    DYNAMIC_ART_STICKER_GENERATION,
    DYNAMIC_ART_STICKER_SELECTION;

    @Override // defpackage.idt
    public final /* synthetic */ int a() {
        return -1;
    }

    @Override // defpackage.idt
    public final /* synthetic */ String b() {
        return "";
    }
}
