package defpackage;

/* compiled from: PG */
/* renamed from: cwe  reason: default package */
/* loaded from: classes.dex */
public final class cwe {
    public static final llr a;

    static {
        lmh lmhVar = new lmh();
        llq.b("angel", "angel", lmhVar);
        llq.b("anger", "anger", lmhVar);
        llq.b("annoyed", "annoyed", lmhVar);
        llq.b("awesome", "awesome", lmhVar);
        llq.b("balloon", "balloon", lmhVar);
        llq.b("beer", "beer", lmhVar);
        llq.b("bicep", "chin ups", lmhVar);
        llq.b("birthday", "birthday", lmhVar);
        llq.b("blow kiss", "blow kiss", lmhVar);
        llq.b("blue heart", "blue heart", lmhVar);
        llq.b("bowing", "bow", lmhVar);
        llq.b("bunny dance", "bunny", lmhVar);
        llq.b("cake", "cake", lmhVar);
        llq.b("call me", "call me", lmhVar);
        llq.b("celebration", "celebration", lmhVar);
        llq.b("clown smile", "clown", lmhVar);
        llq.b("coffee", "coffee", lmhVar);
        llq.b("congratulations", "congratulations", lmhVar);
        llq.b("cool", "cool", lmhVar);
        llq.b("couple", "love", lmhVar);
        llq.b("crying", "sad", lmhVar);
        llq.b("dancing", "dancing", lmhVar);
        llq.b("disapproval", "no", lmhVar);
        llq.b("displeasure", "upset", lmhVar);
        llq.b("dizzy", "spinning on head", lmhVar);
        llq.b("downcast", "cast", lmhVar);
        llq.b("drink", "drink", lmhVar);
        llq.b("drool", "drool", lmhVar);
        llq.b("embarrassed", "embarrassed", lmhVar);
        llq.b("explosion", "bomb", lmhVar);
        llq.b("eye roll", "eye roll", lmhVar);
        llq.b("facepalm", "idiot", lmhVar);
        llq.b("fever", "flu", lmhVar);
        llq.b("fist", "fist", lmhVar);
        llq.b("fistbump", "fist bump", lmhVar);
        llq.b("flower", "flower", lmhVar);
        llq.b("frown", "smile", lmhVar);
        llq.b("gift", "gift", lmhVar);
        llq.b("good luck", "good luck", lmhVar);
        llq.b("green heart", "green", lmhVar);
        llq.b("grimace", "kissy face", lmhVar);
        llq.b("grinning", "smile", lmhVar);
        llq.b("handshake", "fist shake", lmhVar);
        llq.b("hear no evil", "hear no evil", lmhVar);
        llq.b("heart", "heart", lmhVar);
        llq.b("heart broken", "heart break", lmhVar);
        llq.b("heart eyes", "heart", lmhVar);
        llq.b("hearty blush", "heart", lmhVar);
        llq.b("high five", "high five", lmhVar);
        llq.b("horns", "horns", lmhVar);
        llq.b("hug", "hugs", lmhVar);
        llq.b("hurt", "hurt", lmhVar);
        llq.b("kiss", "kiss", lmhVar);
        llq.b("laugh", "laugh", lmhVar);
        llq.b("laughing crying", "laughing crying", lmhVar);
        llq.b("lips", "lips", lmhVar);
        llq.b("moon", "moon", lmhVar);
        llq.b("nerdy", "nerd", lmhVar);
        llq.b("night", "night", lmhVar);
        llq.b("oh no", "oh no", lmhVar);
        llq.b("okay", "great", lmhVar);
        llq.b("open hands", "open sign", lmhVar);
        llq.b("orange heart", "orange", lmhVar);
        llq.b("perfect score", "perfect", lmhVar);
        llq.b("pleading face", "kissy face", lmhVar);
        llq.b("please", "please", lmhVar);
        llq.b("pout", "kissy face", lmhVar);
        llq.b("pride", "pride", lmhVar);
        llq.b("purple heart", "purple", lmhVar);
        llq.b("quiet", "quiet", lmhVar);
        llq.b("raised eyebrow", "eyebrows", lmhVar);
        llq.b("relieved", "relieved", lmhVar);
        llq.b("rofl", "rofl", lmhVar);
        llq.b("rose", "rose", lmhVar);
        llq.b("sad but relieved", "sad lol", lmhVar);
        llq.b("scream", "scream", lmhVar);
        llq.b("scrunchy", "chair", lmhVar);
        llq.b("see no evil", "see no evil", lmhVar);
        llq.b("shrug", "gasp", lmhVar);
        llq.b("shush", "shh", lmhVar);
        llq.b("sickness", "getting sick", lmhVar);
        llq.b("sigh", "sigh", lmhVar);
        llq.b("sleepiness", "sleep", lmhVar);
        llq.b("smile", "smile", lmhVar);
        llq.b("smiling blush", "blush", lmhVar);
        llq.b("smirk", "smile", lmhVar);
        llq.b("squinting laugh", "laughing", lmhVar);
        llq.b("star", "star", lmhVar);
        llq.b("starstruck", "great", lmhVar);
        llq.b("sun", "sun", lmhVar);
        llq.b("sweaty", "sweaty", lmhVar);
        llq.b("teary", "tears", lmhVar);
        llq.b("thinking", "thinking", lmhVar);
        llq.b("tipping hand", "thumb out", lmhVar);
        llq.b("tongue stick", "tongue", lmhVar);
        llq.b("ugh", "ugh", lmhVar);
        llq.b("upside down", "upside down", lmhVar);
        llq.b("vomit", "vomit", lmhVar);
        llq.b("waving", "wave", lmhVar);
        llq.b("whatever", "whatever", lmhVar);
        llq.b("wink", "wink", lmhVar);
        llq.b("worried", "worried", lmhVar);
        llq.b("yawn", "yawn", lmhVar);
        llq.b("yellow heart", "yellow", lmhVar);
        llq.b("yum", "yum", lmhVar);
        a = llq.a(lmhVar);
    }
}
