package defpackage;

/* compiled from: PG */
/* renamed from: ecc  reason: default package */
/* loaded from: classes.dex */
final class ecc {
    static final lmz a = lmz.w("el", "los", "las", "al", "como", "con", "del", "desde", "es", "está", "puede", "cuando", "tiene", "hasta", "también", "página", "ya", "más", "le", "otros", "y", "pero", "entre", "son", "que", "un", "una", "no", "su", "todos", "o", "lo", "la", "de", "or");
    static final llw b;

    static {
        lls i = llw.i(155);
        i.a("admiration", "felicidades");
        i.a("aggressiveness", "cara arrugada");
        i.a("alien", "extraterrestre");
        i.a("amusement", "jaja");
        i.a("angel", "ángel");
        i.a("anger", "enojado");
        i.a("annoyance", "irritado");
        i.a("apple", "manzana");
        i.a("approval", "Pulgares hacia arriba");
        i.a("asap", "cuanto antes");
        i.a("away", "estoy fuera");
        i.a("balloon", "globo");
        i.a("banana", "plátano");
        i.a("baseball", "béisbol");
        i.a("basketball", "baloncesto");
        i.a("bbq", "barbacoa");
        i.a("bear", "oso");
        i.a("bee", "abeja");
        i.a("books", "libros");
        i.a("brb", "brb");
        i.a("bunny", "conejito");
        i.a("burger", "hamburguesa");
        i.a("bye", "adiós");
        i.a("call_me", "Llámame");
        i.a("car", "conducir");
        i.a("cat", "gato");
        i.a("celebration", "celebracion");
        i.a("celebration_cake", "cumpleaños");
        i.a("cheering", "aplausos");
        i.a("cheers", "salud");
        i.a("cherry", "Cereza");
        i.a("chick", "pollo");
        i.a("chicken", "pollo");
        i.a("chocolate", "chocolate");
        i.a("christmas_tree", "árbol de Navidad");
        i.a("cloud", "nube");
        i.a("coffee", "café");
        i.a("confusion", "confuso");
        i.a("cookie", "Galleta");
        i.a("crown", "reina");
        i.a("dancing", "baile");
        i.a("diamond", "diamante");
        i.a("disapproval", "pulgares abajo");
        i.a("disgust", "vómito");
        i.a("do_not_disturb", "No molestar");
        i.a("dog", "perro");
        i.a("dolphin", "delfín");
        i.a("doubt", "duda");
        i.a("doughnut", "rosquilla");
        i.a("down", "señalar hacia abajo");
        i.a("dress", "vestir");
        i.a("drinks", "bebidas");
        i.a("drooling", "babeando");
        i.a("drops", "sudor");
        i.a("earth", "tierra");
        i.a("embarrassment", "conmocionado");
        i.a("explosion", "explosión");
        i.a("eye_roll", "eyeroll");
        i.a("eyes", "ojos");
        i.a("facepalm", "carapalm");
        i.a("fear", "Dios mio");
        i.a("fire", "calor");
        i.a("fish", "pez");
        i.a("fist", "puño");
        i.a("fistbump", "choca los puños");
        i.a("flower", "flor");
        i.a("football", "fútbol americano");
        i.a("friend", "te quiero amiga");
        i.a("frog", "rana");
        i.a("for_the_win", "ganar");
        i.a("ghost", "escalofriante");
        i.a("good_luck", "buena suerte");
        i.a("grapes", "uvas");
        i.a("groggy", "mareado");
        i.a("hand", "Cinco altos");
        i.a("hanging_out", "pasando el rato");
        i.a("hear_no_evil", "silencio");
        i.a("heartbroken", "desconsolado");
        i.a("help", "ayuda");
        i.a("hi", "Hola");
        i.a("horns", "rock");
        i.a("horse", "caballo");
        i.a("hot", "cara de calor");
        i.a("house", "casa");
        i.a("ice_cream", "helado");
        i.a("indifference", "decepcionado");
        i.a("innocent", "inocente");
        i.a("joy", "alegría");
        i.a("leaf", "hoja");
        i.a("left", "apuntando");
        i.a("lightning_bolt", "rayo");
        i.a("love", "te amo");
        i.a("mail", "correo");
        i.a("meh", "meh");
        i.a("mic", "mic");
        i.a("money", "dinero");
        i.a("moon", "buenas noches");
        i.a("movies", "películas");
        i.a("music", "música");
        i.a("nerdy", "nerd");
        i.a("nervousness", "nervioso");
        i.a("night", "noche");
        i.a("oh_no", "Oh no");
        i.a("oops", "Uy");
        i.a("optimism", "dedos cruzados");
        i.a("ouch", "Ay");
        i.a("panda", "panda");
        i.a("peace", "paz");
        i.a("pensiveness", "pensando");
        i.a("perfect_score", "100");
        i.a("phone", "teléfono");
        i.a("pizza", "Pizza");
        i.a("plane", "avión");
        i.a("please", "Por favor");
        i.a("praying", "Orando");
        i.a("present", "regalo");
        i.a("pumpkin", "calabaza");
        i.a("rain", "lluvia");
        i.a("rainbow", "arco iris");
        i.a("ribbon", "cinta");
        i.a("right", "apuntando");
        i.a("sadness", "triste");
        i.a("see_no_evil", "no quiero ver");
        i.a("serenity", "aliviado");
        i.a("shower", "ducha");
        i.a("sickness", "enfermo");
        i.a("silence", "shh");
        i.a("sleepiness", "soñoliento");
        i.a("smirk", "presumido");
        i.a("smugness", "presumido");
        i.a("snow", "frío");
        i.a("soccer_ball", "balón de fútbol");
        i.a("squid", "calamar");
        i.a("star", "estrella");
        i.a("strawberry", "fresa");
        i.a("strength", "fuerte");
        i.a("sun", "Buenos días");
        i.a("surprised", "sorprendido");
        i.a("sweaty", "nervioso");
        i.a("thanks", "Gracias");
        i.a("tic_toc", "TIC Toc");
        i.a("tiger", "Tigre");
        i.a("tomato", "tomate");
        i.a("turtle", "Tortuga");
        i.a("undecided", "hmm");
        i.a("up", "apuntando");
        i.a("watch", "reloj");
        i.a("watermelon", "sandía");
        i.a("waving", "saludar");
        i.a("what", "qué");
        i.a("what's_up", "Qué pasa");
        i.a("wine", "vino");
        i.a("wink", "guiño");
        i.a("yum", "ñam");
        i.a("ttyl", "Adiós");
        b = i.l();
    }
}
