package defpackage;

/* JADX INFO: Access modifiers changed from: package-private */
/* compiled from: PG */
/* renamed from: jax  reason: default package */
/* loaded from: classes.dex */
public final class jax {
    public static final llp a = llp.x(jav.f("en-US"), jav.f("ar-EG"), jav.f("zh-CN"), jav.f("zh-TW"), jav.f("nl-NL"), jav.f("en-GB"), jav.f("fr-FR"), jav.f("de-DE"), jav.f("it-IT"), jav.f("ja-JP"), jav.f("ko-KR"), jav.f("pl-PL"), jav.f("pt-BR"), jav.f("ru-RU"), jav.f("es-ES"), jav.f("th-TH"), jav.f("tr-TR"), jav.f("es-419"), jav.f("bg-BG"), jav.f("ca-ES"), jav.f("hr-HR"), jav.f("cs-CZ"), jav.f("da-DK"), jav.f("tl-PH"), jav.f("fi-FI"), jav.f("el-GR"), jav.f("iw-IL"), jav.f("hi-IN"), jav.f("hi-Latn-IN"), jav.f("hu-HU"), jav.f("in-ID"), jav.f("lv-LV"), jav.f("lt-LT"), jav.f("nb-NO"), jav.f("pt-PT"), jav.f("ro-RO"), jav.f("sr-Cyrl-RS"), jav.f("sk-SK"), jav.f("sl-SI"), jav.f("sv-SE"), jav.f("uk-UA"), jav.f("vi-VN"), jav.f("fa-IR"), jav.f("af-ZA"), jav.f("bn-BD"), jav.f("bn-IN"), jav.f("et-EE"), jav.f("is-IS"), jav.f("ms-MY"), jav.f("mr-IN"), jav.f("sw-TZ"), jav.f("ta-IN"), jav.f("sq-AL"), jav.f("hy-AM"), jav.f("az-AZ"), jav.f("my-MM"), jav.f("ka-GE"), jav.f("kk-KZ"), jav.f("km-KH"), jav.f("lo-LA"), jav.f("mk-MK"), jav.f("mn-MN"), jav.f("ne-NP"), jav.f("si-LK"), jav.f("am-ET"), jav.f("gu-IN"), jav.f("kn-IN"), jav.f("ml-IN"), jav.f("te-IN"), jav.f("ur-PK"), jav.f("ky-KG"), jav.f("pa-Guru-IN"), jav.f("uz-UZ"), jav.f("sr-Latn-RS"), jav.f("es-US"), jav.f("es-MX"), jav.f("en-CA"), jav.f("en-AU"), jav.f("fr-CA"), jav.f("de-CH"), jav.f("zh-HK"), jav.f("ar-DZ"), jav.f("ur-IN"), jav.f("or-IN"), jav.f("as-IN"), jav.f("mai-IN"), jav.f("sat-Beng-IN"), jav.f("sat-Olck-IN"), jav.f("sat-Latn-IN"), jav.f("ks-Deva-IN"), jav.f("ks-Arab-IN"), jav.f("ne-IN"), jav.f("kok-Deva-IN"), jav.f("kok-Latn-IN"), jav.f("sd-Deva-IN"), jav.f("sd-Arab-IN"), jav.f("doi-Deva-IN"), jav.f("doi-Arab-IN"), jav.f("mni-Beng-IN"), jav.f("mni-Mtei-IN"), jav.f("brx-Deva-IN"), jav.f("brx-Beng-IN"), jav.f("sa-IN"), jav.f("en-IN"));
}
